### PR TITLE
report back to success, #1

### PR DESCRIPTION
**Pull request by koshuang**

### CODE REVIEW

**Comment by jdcataldo** [comment]
Looks good. Can you change it to be off by default? Would prefer people to opt-in to new features.

**Comment by pascalpp** [comment]
ping. just wrote a version of this myself, now I see it's already been done :) @koshuang can you update the conflicts in your PR so it can be merged?

**Comment by koshuang** [comment]
@pascalpp I almost forgot, thanks! Will do it. :)

**Comment by koshuang** [comment]
@jdcataldo I created a new commit, not sure if this is okay. Do you have time to review? thanks!

**Pull request merged**
